title: Jacob M. Lundeen # your name (or website title) here
logo: "/images/CCI_000001.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A US Army veteran and analyst with data science, statistics, machine learning, programming, and management background. 
  Over six years of statistical data analysis and reporting. Experienced communicator having briefed internal and external 
  stakeholders on analysis findings and courses of action. 
  <br><br>
  Second description 
  <br><br>
  <a href="https://github.com/jacoblundeen">View My GitHub Profile</a>
  <br><br>
  <a href="https://www.linkedin.com/in/jacob-lundeen-b49b8390/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://rpubs.com/jacoblundeen">View My RPubs Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
